server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  hikari:
    maximum-pool-size: 5
