server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/contacts
    username: postgres
    password: postgres
    hikari:
      schema: contacts_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS contacts_schema
      connection-timeout: 10000

logging:
  level:
    org.springframework.jdbc.core: TRACE